export const quizData = [
  {
    title: 'Animal Sounds',
    question: 'What sound does a cow make?',
    answers: ['Oink', 'Moo', 'Meow', 'Woof'],
    correctAnswer: 'Moo',
  },
  {
    title: 'Big Animals',
    question: 'Which animal is the biggest in the world?',
    answers: ['Elephant', 'Giraffe', 'Blue Whale', 'Lion'],
    correctAnswer: 'Blue Whale',
  },
  {
    title: 'Plant Growth',
    question: 'What do plants need to grow big and strong?',
    answers: ['Sunshine', 'Cookies', 'Toys', 'Blankets'],
    correctAnswer: 'Sunshine',
  },
  {
    title: 'Baby Animals',
    question: 'What is a baby cat called?',
    answers: ['Puppy', 'Kitten', 'Cub', 'Fawn'],
    correctAnswer: 'Kitten',
  },
  {
    title: 'Colors in Nature',
    question: 'What color is a banana?',
    answers: ['Red', 'Blue', 'Yellow', 'Green'],
    correctAnswer: 'Yellow',
  },
  {
    title: 'Where Animals Live',
    question: 'Where do fish live?',
    answers: ['In the sky', 'In a house', 'In the water', 'In a tree'],
    correctAnswer: 'In the water',
  },
  {
    title: 'Busy Insects',
    question: 'Which insect makes sweet honey?',
    answers: ['Bee', 'Ant', 'Ladybug', 'Spider'],
    correctAnswer: 'Bee',
  },
  {
    title: 'The Sky',
    question: 'What shines in the sky during the day?',
    answers: ['The Moon', 'The Sun', 'A lamp', 'Stars'],
    correctAnswer: 'The Sun',
  },
  {
    title: 'Farm Animals',
    question: 'Which animal gives us eggs?',
    answers: ['Pig', 'Cow', 'Chicken', 'Sheep'],
    correctAnswer: 'Chicken',
  },
  {
    title: 'Tall Trees',
    question: 'What grows on trees?',
    answers: ['Fish', 'Rocks', 'Leaves', 'Cars'],
    correctAnswer: 'Leaves',
  },
  {
    title: 'Animal Noses',
    question: 'What is a pig\'s nose called?',
    answers: ['Trunk', 'Beak', 'Snout', 'Muzzle'],
    correctAnswer: 'Snout',
  },
  {
    title: 'Night Sky',
    question: 'What do we see in the sky at night?',
    answers: ['The Sun', 'Rainbows', 'The Moon and Stars', 'Clouds only'],
    correctAnswer: 'The Moon and Stars',
  },
  {
    title: 'Fuzzy Animals',
    question: 'Which animal is known for its soft wool?',
    answers: ['Goat', 'Horse', 'Sheep', 'Donkey'],
    correctAnswer: 'Sheep',
  },
  {
    title: 'Weather',
    question: 'What falls from the clouds when it rains?',
    answers: ['Sunshine', 'Water', 'Snow', 'Juice'],
    correctAnswer: 'Water',
  },
  {
    title: 'Forest Animals',
    question: 'Which animal loves to eat nuts?',
    answers: ['Frog', 'Squirrel', 'Fish', 'Bird'],
    correctAnswer: 'Squirrel',
  },
  {
    title: 'Colorful Birds',
    question: 'Which bird is known for its beautiful, colorful feathers?',
    answers: ['Crow', 'Pigeon', 'Peacock', 'Sparrow'],
    correctAnswer: 'Peacock',
  },
  {
    title: 'What Frogs Do',
    question: 'What are frogs good at?',
    answers: ['Flying', 'Running', 'Jumping', 'Singing'],
    correctAnswer: 'Jumping',
  },
  {
    title: 'Slow Animals',
    question: 'Which animal moves very, very slowly?',
    answers: ['Cheetah', 'Rabbit', 'Snail', 'Horse'],
    correctAnswer: 'Snail',
  },
  {
    title: 'Baby Dogs',
    question: 'What is a baby dog called?',
    answers: ['Kitten', 'Puppy', 'Calf', 'Joey'],
    correctAnswer: 'Puppy',
  },
  {
    title: 'Striped Animals',
    question: 'Which animal has black and white stripes?',
    answers: ['Lion', 'Tiger', 'Zebra', 'Bear'],
    correctAnswer: 'Zebra',
  },
];